<?php
$google_fonts_array = knacc_google_fonts();

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_blog-page-layout',
		'title' => 'Blog Page Layout',
		'fields' => array (
			array (
				'key' => 'field_53343b5f2f805',
				'label' => 'Blog Page Layout',
				'name' => 'blog_page_layout',
				'type' => 'select',
				'instructions' => 'Which layout do you want to use for your blog page? Standard list or Masonry style?',
				'choices' => array (
					'standard' => 'Standard List Style',
					'masonry' => 'Masonry Style',
				),
				'default_value' => 'standard',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_53343c6a5ca10',
				'label' => 'Number of Columns',
				'name' => 'blog_layout_columns',
				'type' => 'select',
				'instructions' => 'How many columns do you want to use for the Masonry layout?',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53343b5f2f805',
							'operator' => '==',
							'value' => 'masonry',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					2 => 'Two Columns',
					3 => 'Three Columns',
					4 => 'Four Columns',
				),
				'default_value' => 3,
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'posts_page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog-post-audio',
		'title' => 'Blog Post Audio',
		'fields' => array (
			array (
				'key' => 'field_53174078321ab',
				'label' => 'Audio Upload',
				'name' => 'post_audio_upload',
				'type' => 'file',
				'instructions' => 'Upload or select a audio file from the Media Library',
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_531740ac321ac',
				'label' => 'Audio URL',
				'name' => 'post_audio_url',
				'type' => 'text',
				'instructions' => 'Enter a URL to your audio file here',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'audio',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_blog-post-video',
		'title' => 'Blog Post Video',
		'fields' => array (
			array (
				'key' => 'field_53173d079cf01',
				'label' => 'Video Upload',
				'name' => 'post_video_upload',
				'type' => 'file',
				'instructions' => 'Upload or select a video from the media library',
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_53752cd2f8d40',
				'label' => 'Poster Image',
				'name' => 'poster_image',
				'type' => 'image',
				'instructions' => 'Add a image here to show as a still frame to represent your UPLOADED video when it\'s not playing. (Ratio should be 16:9)',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_53173db3a618d',
				'label' => 'Video URL',
				'name' => 'post_video_url',
				'type' => 'text',
				'instructions' => 'Add the URL to your video here',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53173fd602fea',
				'label' => 'Video Embed Code',
				'name' => 'video_embed',
				'type' => 'textarea',
				'instructions' => 'Add your video embed code here',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
				'rows' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_contact-details',
		'title' => 'Contact Details',
		'fields' => array (
			array (
				'key' => 'field_530b535197a3c',
				'label' => 'Display Contact Details',
				'name' => 'display_contact_details',
				'type' => 'true_false',
				'instructions' => 'Do you want to display the contact details?',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_530b51f910c47',
				'label' => 'Phone',
				'name' => 'phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b523310c48',
				'label' => 'Mobile',
				'name' => 'mobile',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b527010c49',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_530b52a110c4a',
				'label' => 'Address Line 1',
				'name' => 'address_line_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b52ad10c4b',
				'label' => 'Address Line 2',
				'name' => 'address_line_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b52c210c4c',
				'label' => 'Town / City',
				'name' => 'town_city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b52d110c4d',
				'label' => 'State / County',
				'name' => 'state_county',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b52ef10c4e',
				'label' => 'Country',
				'name' => 'country',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b532f599d5',
				'label' => 'Zip / Postcode',
				'name' => 'zip_postcode',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_custom-css',
		'title' => 'Custom CSS',
		'fields' => array (
			array (
				'key' => 'field_5315e96457c91',
				'label' => 'Custom CSS',
				'name' => 'custom_css',
				'type' => 'textarea',
				'instructions' => 'For minor custom css changes you can add your css here. For any major changes / additions you should use a child theme. (See theme documentation)',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
				'rows' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_google-map-options',
		'title' => 'Google Map Options',
		'fields' => array (
			array (
				'key' => 'field_530b39130653b',
				'label' => 'Display Google Map',
				'name' => 'display_google_map',
				'type' => 'true_false',
				'instructions' => 'Do you want to display the Google Map?',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_530b346b788c6',
				'label' => 'Google Map Address',
				'name' => 'google_map_address',
				'type' => 'text',
				'instructions' => 'Enter here your address zipcode or postcode to set the location you want to use for the Google Map',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530b353cf9177',
				'label' => 'Google Map Zoom',
				'name' => 'google_map_zoom',
				'type' => 'select',
				'choices' => array (
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					13 => 13,
					14 => 14,
					15 => 15,
					16 => 16,
					17 => 17,
					18 => 18,
					19 => 19,
					20 => 20,
				),
				'default_value' => 12,
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-fullscreen-slider',
		'title' => 'Home Fullscreen Slider',
		'fields' => array (
			array (
				'key' => 'field_53330df3d3bde',
				'label' => 'Home Fullscreen Slider',
				'name' => 'home_slider_alias',
				'type' => 'text',
				'instructions' => 'To display your fullscreen slider on the homepage template, first create your slider within the Revolution slider plugin. Then add the slider alias into this field and your slider will display. Be sure to create a fullscreen slider within the plugin.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-home.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'discussion',
				1 => 'comments',
				2 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-background',
		'title' => 'Page Background',
		'fields' => array (
			array (
				'key' => 'field_531726711402d',
				'label' => 'Page Background Colour',
				'name' => 'page_background_colour',
				'type' => 'color_picker',
				'instructions' => 'Select a colour here if you want to set a specific background colour for this page',
				'default_value' => '',
			),
			array (
				'key' => 'field_5334078186899',
				'label' => 'Page Background Image',
				'name' => 'page_background_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53341b56e2cb5',
				'label' => 'Page Background Image Repeat',
				'name' => 'page_background_image_repeat',
				'type' => 'select',
				'instructions' => 'Do you want your background image to repeat or not?',
				'choices' => array (
					'repeat' => 'Repeat',
					'no-repeat' => 'No Repeat',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-header',
		'title' => 'Page Header',
		'fields' => array (
			array (
				'key' => 'field_533315379e706',
				'label' => 'Display Page Header?',
				'name' => 'display_page_header',
				'type' => 'true_false',
				'instructions' => 'Do you want to display the page header for this page? Displayed by default.',
				'message' => '',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-image',
		'title' => 'Portfolio Image',
		'fields' => array (
			array (
				'key' => 'field_52f8d6c93f351',
				'label' => 'Image Upload',
				'name' => 'lightbox_image_upload',
				'type' => 'file',
				'instructions' => 'Upload or use a image from the Media Library',
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_52f8d6ea3f352',
				'label' => 'Image URL',
				'name' => 'lightbox_image_url',
				'type' => 'text',
				'instructions' => 'OR enter an external image URL',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'image',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-link',
		'title' => 'Portfolio Link',
		'fields' => array (
			array (
				'key' => 'field_52f8d74b94efa',
				'label' => 'External Link',
				'name' => 'external_link',
				'type' => 'text',
				'instructions' => 'Enter an external URL for this post to link to',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'link',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-post-type-options',
		'title' => 'Portfolio Post Type Options',
		'fields' => array (
			array (
				'key' => 'field_52fa1c4642b62',
				'label' => 'Portfolio Post Type Label',
				'name' => 'portfolio_post_type_label',
				'type' => 'text',
				'instructions' => 'Enter a value here to change the default label for the portfolio post type. For example you could change \'Portfolio\' to \'Work\'.',
				'default_value' => 'Portfolio',
				'placeholder' => 'Portfolio',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52fa1c9d42b63',
				'label' => 'Portfolio Post Type Slug',
				'name' => 'portfolio_post_type_slug',
				'type' => 'text',
				'instructions' => 'Enter a value here to change the default slug for the portfolio post type',
				'default_value' => 'portfolio',
				'placeholder' => 'portfolio',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-standard',
		'title' => 'Portfolio Standard',
		'fields' => array (
			array (
				'key' => 'field_52f57b059529c',
				'label' => 'Portfolio Images',
				'name' => 'portfolio_images',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_530723c6ed1ed',
						'label' => 'Image Type',
						'name' => 'image_type',
						'type' => 'select',
						'required' => 1,
						'column_width' => '',
						'choices' => array (
							'upload' => 'Image Upload',
							'url' => 'Image URL',
						),
						'default_value' => 'upload',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52f57b979529d',
						'label' => 'Image Upload',
						'name' => 'image_upload',
						'type' => 'file',
						'instructions' => 'Upload or use a image from the Media Library',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_530723c6ed1ed',
									'operator' => '==',
									'value' => 'upload',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => 50,
						'save_format' => 'object',
						'library' => 'all',
					),
					array (
						'key' => 'field_52f57bcc9529e',
						'label' => 'Image URL',
						'name' => 'image_url',
						'type' => 'text',
						'instructions' => 'Enter a image URL (Including http://)',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_530723c6ed1ed',
									'operator' => '==',
									'value' => 'url',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => 50,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'http://',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Image',
			),
			array (
				'key' => 'field_52f577254771c',
				'label' => 'Image Slider',
				'name' => 'image_slider',
				'type' => 'true_false',
				'instructions' => 'Do you want to use a slider to display these images?',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'standard',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-top-slider',
		'title' => 'Portfolio Top Slider',
		'fields' => array (
			array (
				'key' => 'field_53329e6561a09',
				'label' => 'Portfolio Top Slider Alias',
				'name' => 'portfolio_top_slider_alias',
				'type' => 'text',
				'instructions' => 'To add a slider to the top of your portfolio page, create slider using the Revolution Slider plugin and then add in the slider alias in this field and your slider will display',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-portfolio.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-video',
		'title' => 'Portfolio Video',
		'fields' => array (
			array (
				'key' => 'field_52f8ceff90d7b',
				'label' => 'Portfolio Videos',
				'name' => 'portfolio_videos',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53071c753e48c',
						'label' => 'Video Type',
						'name' => 'video_type',
						'type' => 'select',
						'required' => 1,
						'column_width' => 100,
						'choices' => array (
							'upload' => 'Video Upload',
							'url' => 'Video URL',
							'embed' => 'Video Embed',
						),
						'default_value' => 'upload',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_52f8d34a90d7c',
						'label' => 'Video Upload',
						'name' => 'video_upload',
						'type' => 'file',
						'instructions' => 'Upload or use a video from the Media Library',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53071c753e48c',
									'operator' => '==',
									'value' => 'upload',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => 100,
						'save_format' => 'url',
						'library' => 'all',
					),
					array (
						'key' => 'field_52f8d38d90d7d',
						'label' => 'Video URL',
						'name' => 'video_url',
						'type' => 'text',
						'instructions' => 'Enter a video URL',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53071c753e48c',
									'operator' => '==',
									'value' => 'url',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => 100,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => 'http://',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_530722fcedd07',
						'label' => 'Video Embed',
						'name' => 'video_embed',
						'type' => 'textarea',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53071c753e48c',
									'operator' => '==',
									'value' => 'embed',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'Add your video embed code here...',
						'maxlength' => '',
						'formatting' => 'html',
						'rows' => '',
					),
					array (
						'key' => 'field_53752a8b39d5c',
						'label' => 'Poster Image',
						'name' => 'poster_image',
						'type' => 'image',
						'instructions' => 'Add a image here to show as a still frame to represent your video when it\'s not playing. (Ratio should be 16:9)',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53071c753e48c',
									'operator' => '==',
									'value' => 'upload',
								),
								array (
									'field' => 'field_53071c753e48c',
									'operator' => '==',
									'value' => 'url',
								),
							),
							'allorany' => 'any',
						),
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'full',
						'library' => 'all',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Video',
			),
			array (
				'key' => 'field_52f8d4232d39a',
				'label' => 'Video Slider',
				'name' => 'video_slider',
				'type' => 'true_false',
				'instructions' => 'If you have multiple videos, do you want to use a slider to display the videos?',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_profile-details',
		'title' => 'Profile Details',
		'fields' => array (
			array (
				'key' => 'field_531791ecf3f64',
				'label' => 'Profile Name',
				'name' => 'profile_name',
				'type' => 'text',
				'instructions' => 'Enter your name here to show as your profile name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_531793472a2ae',
				'label' => 'Job Title / Occupaction',
				'name' => 'profile_job_title',
				'type' => 'text',
				'instructions' => 'Enter your job title / occupation here to show underneath your profile name',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53186b31d05c2',
				'label' => 'Profile Icons',
				'name' => 'profile_icons',
				'type' => 'text',
				'instructions' => 'This field can be used for adding social icons (see documentation) or some random line of text under your profile name.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53179224f3f65',
				'label' => 'Featured Text',
				'name' => 'profile_featured_text',
				'type' => 'wysiwyg',
				'instructions' => 'Enter some lead text here to show within the featured text area',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_531792c4f3f66',
				'label' => 'Profile Image',
				'name' => 'profile_image',
				'type' => 'image',
				'instructions' => 'Add a profile image here (180 x 180px)',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-profile.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_site-logo',
		'title' => 'Site Logo',
		'fields' => array (
			array (
				'key' => 'field_52fa3adce5f5c',
				'label' => 'Site Logo',
				'name' => 'site_logo',
				'type' => 'image',
				'instructions' => 'Upload a logo here for your site',
				'save_format' => 'object',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_social-networks',
		'title' => 'Social Networks',
		'fields' => array (
			array (
				'key' => 'field_5317a64cf8c3c',
				'label' => 'Facebook URL',
				'name' => 'social_facebook',
				'type' => 'text',
				'instructions' => 'e.g. http://www.facebook.com/username',
				'default_value' => '',
				'placeholder' => 'http://www.facebook.com/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5317a681f8c3e',
				'label' => 'Twitter URL',
				'name' => 'social_twitter',
				'type' => 'text',
				'instructions' => 'e.g. http://twitter.com/username',
				'default_value' => '',
				'placeholder' => 'http://twitter.com/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5317a8240cc34',
				'label' => 'Vimeo URL',
				'name' => 'social_vimeo',
				'type' => 'text',
				'instructions' => 'e.g. http://vimeo.com/username',
				'default_value' => '',
				'placeholder' => 'http://vimeo.com/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5317a8720cc35',
				'label' => 'YouTube URL',
				'name' => 'social_youtube',
				'type' => 'text',
				'instructions' => 'e.g. http://www.youtube.com/user/username',
				'default_value' => '',
				'placeholder' => 'http://www.youtube.com/user/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5317a8900cc36',
				'label' => 'Pinterest URL',
				'name' => 'social_pinterest',
				'type' => 'text',
				'instructions' => 'e.g. http://pinterest.com/username',
				'default_value' => '',
				'placeholder' => 'http://pinterest.com/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5317a8e80cc37',
				'label' => 'Google Plus URL',
				'name' => 'social_google',
				'type' => 'text',
				'instructions' => 'e.g. http://plus.google.com/userID',
				'default_value' => '',
				'placeholder' => 'http://plus.google.com/userID',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5317b2a32a040',
				'label' => 'Behance URL',
				'name' => 'social_behance',
				'type' => 'text',
				'instructions' => ' e.g. http://www.behance.net/username',
				'default_value' => '',
				'placeholder' => 'http://www.behance.net/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5317b38b9a56f',
				'label' => 'Instagram URL',
				'name' => 'social_instagram',
				'type' => 'text',
				'instructions' => 'e.g. http://instagram.com/username',
				'default_value' => '',
				'placeholder' => 'http://instagram.com/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53690521f372e',
				'label' => 'Dribbble URL',
				'name' => 'social_dribbble',
				'type' => 'text',
				'instructions' => 'e.g. https://dribbble.com/username',
				'default_value' => '',
				'placeholder' => 'https://dribbble.com/username',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_536905c5a4079',
				'label' => 'LinkedIn URL',
				'name' => 'social_linkedin',
				'type' => 'text',
				'instructions' => 'e.g. https://www.linkedin.com/profile/view?id=00000000',
				'default_value' => '',
				'placeholder' => 'https://www.linkedin.com/profile/view?id=00000000',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-social',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_team-members',
		'title' => 'Team Members',
		'fields' => array (
			array (
				'key' => 'field_5317bfec064fe',
				'label' => 'Team Members',
				'name' => 'team_members',
				'type' => 'repeater',
				'instructions' => 'Add your team members here',
				'sub_fields' => array (
					array (
						'key' => 'field_5317c01f064ff',
						'label' => 'Member Name',
						'name' => 'member_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5317c0665c226',
						'label' => 'Member Job Title',
						'name' => 'member_job_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5317c08c5c227',
						'label' => 'Member Image',
						'name' => 'member_image',
						'type' => 'file',
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'all',
					),
					array (
						'key' => 'field_53185f05d7b28',
						'label' => 'Member Icons',
						'name' => 'member_icons',
						'type' => 'text',
						'instructions' => 'This field can be used for adding social icons (see documentation) or some text for each team member.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 2,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Member',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-team.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_theme-colours',
		'title' => 'Theme Colours',
		'fields' => array (
			array (
				'key' => 'field_52fa243d798f8',
				'label' => 'Theme Colour Skin',
				'name' => 'colour_skin',
				'type' => 'image_select',
				'instructions' => 'Select a pre-designed colour skin for the theme',
				'choices' => array (
					'skin-none' => 'No Skin (Default)',
					'skin-leaf' => 'Leaf Skin',
					'skin-aqua' => 'Aqua Skin',
					'skin-night' => 'Night Skin',
					'skin-rose' => 'Rose Skin',
					'skin-wine' => 'Wine Skin',
					'skin-earth' => 'Earth Skin',
				),
				'default_value' => 'skin-none',
				'multiple' => 0,
				'image_path' => get_template_directory_uri() . '/images/options/',
				'image_extension' => 'png',
			),
			array (
				'key' => 'field_52fa25099510e',
				'label' => 'Skin Colour Contrast',
				'name' => 'colour_contrast',
				'type' => 'image_select',
				'instructions' => 'Do you want the sidebar to be light or dark?',
				'choices' => array (
					'contrast-sb-dark-bg-light' => 'Dark Sidebar / Light Background',
					'contrast-sb-light-bg-dark' => 'Light Sidebar / Dark Background',
					'contrast-sb-light-bg-light' => 'Light Sidebar / Light Background',
					'contrast-sb-dark-bg-dark' => 'Dark Sidebar / Dark Background',
				),
				'default_value' => 'contrast-sb-dark-bg-light',
				'multiple' => 0,
				'image_path' => get_template_directory_uri() . '/images/options/',
				'image_extension' => 'png',
			),
			array (
				'key' => 'field_52fa3c82c1d64',
				'label' => 'Primary Theme Colour',
				'name' => 'primary_colour',
				'type' => 'color_picker',
				'instructions' => 'Set the primary colour for the theme',
				'default_value' => '',
			),
			array (
				'key' => 'field_52fa406938452',
				'label' => 'Secondary Theme Colour',
				'name' => 'secondary_colour',
				'type' => 'color_picker',
				'instructions' => 'Set the secondary colour for the theme',
				'default_value' => '',
			),
			array (
				'key' => 'field_52fa258aea030',
				'label' => 'Sidebar Background Colour',
				'name' => 'sidebar_background_colour',
				'type' => 'color_picker',
				'instructions' => 'If you want to set a custom background colour for the sidebar, set it here. This will override the selected theme skin.',
				'default_value' => '',
			),
			array (
				'key' => 'field_5315faa981876',
				'label' => 'Sidebar Background Image',
				'name' => 'sidebar_background_image',
				'type' => 'image',
				'instructions' => 'If you want to have a background image to the sidebar instead of a colour then you can set that here.',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_52fa260104ddf',
				'label' => 'Body Background Colour',
				'name' => 'body_background_colour',
				'type' => 'color_picker',
				'instructions' => 'If you want to set a custom background colour for the body, set it here. This will override the selected theme skin.',
				'default_value' => '',
			),
			array (
				'key' => 'field_5315fa191e448',
				'label' => 'Body Background Image',
				'name' => 'body_background_image',
				'type' => 'image',
				'instructions' => 'If you want to have a background image to the body instead of a colour then you can set that here.',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_53172e1774f81',
				'label' => 'Header Background Colour',
				'name' => 'header_background_colour',
				'type' => 'color_picker',
				'instructions' => 'If you want to set a custom background colour for the site header, set it here. This will override the selected theme skin.',
				'default_value' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-design-style',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_footer',
		'title' => 'Footer',
		'fields' => array (
			array (
				'key' => 'field_52fa3b4136efa',
				'label' => 'Footer Text',
				'name' => 'footer_text',
				'type' => 'text',
				'instructions' => 'Add your custom footer text here',
				'default_value' => 'Footer text goes here.... Built by Knacc.',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52fa4368527ec',
				'label' => 'Add Copyright Line',
				'name' => 'add_copyright',
				'type' => 'true_false',
				'instructions' => 'Select if you want the theme to add a copyright line with the current year in the footer. (Format: © Copyright 2014)',
				'message' => '',
				'default_value' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-audio',
		'title' => 'Portfolio Audio',
		'fields' => array (
			array (
				'key' => 'field_52f8d80efc149',
				'label' => 'Audio Upload',
				'name' => 'audio_upload',
				'type' => 'file',
				'instructions' => 'Upload or use a audio file from the Media Library',
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_52f8d831fc14a',
				'label' => 'Audio URL',
				'name' => 'audio_url',
				'type' => 'text',
				'instructions' => 'OR enter an audio file URL',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'audio',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-page-layout',
		'title' => 'Portfolio Page Layout',
		'fields' => array (
			array (
				'key' => 'field_533449b4d7b7d',
				'label' => 'Thumbnail Style',
				'name' => 'portfolio_thumbnail_style',
				'type' => 'select',
				'instructions' => 'Which thumbnail layout style do you want to use?',
				'choices' => array (
					'title-within' => 'Title inside thumbnail (Visible on hover)',
					'title-underneath' => 'Title underneath thumbnail (Always visible)',
				),
				'default_value' => 'title-within',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52fa202468d4c',
				'label' => 'Number of Columns',
				'name' => 'portfolio_columns_number',
				'type' => 'select',
				'instructions' => 'How many columns do you want to display? (This is for a desktop screen, number of columns will automatically reduce for smaller screen sizes)',
				'choices' => array (
					2 => 'Two Columns',
					3 => 'Three Columns',
					4 => 'Four Columns',
					5 => 'Five Columns',
					6 => 'Six Columns',
				),
				'default_value' => 3,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5315ee9a32e22',
				'label' => 'Thumbnail Margin (px)',
				'name' => 'portfolio_thumbnail_margin',
				'type' => 'number',
				'instructions' => 'This option allows you to add spacing (padding) around each portfolio thumbnail image. By default there is no padding.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => 0,
				'max' => 100,
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-portfolio.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_theme-typography',
		'title' => 'Theme Typography',
		'fields' => array (
			array (
				'key' => 'field_52fa269c64c66',
				'label' => 'Headings Font',
				'name' => 'headings_font',
				'type' => 'select',
				'instructions' => 'Set your preferred font for all headings across the theme',
				'choices' => $google_fonts_array,
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52fa334853415',
				'label' => 'Body Font',
				'name' => 'body_font',
				'type' => 'select',
				'instructions' => 'Set your preferred font for body text throughout the theme',
				'choices' => $google_fonts_array,
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52fa350379a7c',
				'label' => 'Body Font Size',
				'name' => 'body_font_size',
				'type' => 'select',
				'instructions' => 'If you want to override the default font size for body text, select a size here',
				'choices' => array (
					10 => '10px',
					12 => '12px',
					14 => '14px',
					16 => '16px',
					18 => '18px',
				),
				'default_value' => 16,
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-design-style',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-single-page-layout',
		'title' => 'Portfolio Single Page Layout',
		'fields' => array (
			array (
				'key' => 'field_53072c8d74509',
				'label' => 'Layout Option',
				'name' => 'portfolio_single_page_layout',
				'type' => 'select',
				'choices' => array (
					'use-global' => 'Use Global Option',
					'layout-fluid' => 'Fluid Layout',
					'layout-fixed' => 'Fixed Layout',
				),
				'default_value' => 'use-global',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-single-page-options',
		'title' => 'Portfolio Single Page Options',
		'fields' => array (
			array (
				'key' => 'field_530734b5e2e21',
				'label' => 'Single Page Layout',
				'name' => 'global_portfolio_single_page_layout',
				'type' => 'select',
				'choices' => array (
					'layout-fluid' => 'Fluid Layout',
					'layout-fixed' => 'Fixed Layout',
				),
				'default_value' => 'layout-fluid',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
	register_field_group(array (
		'id' => 'acf_contact-form',
		'title' => 'Contact Form',
		'fields' => array (
			array (
				'key' => 'field_530b51930d15d',
				'label' => 'Display Contact Form',
				'name' => 'display_contact_form',
				'type' => 'true_false',
				'instructions' => 'Do you want to display the contact form?',
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_530b5f15e6f70',
				'label' => 'Contact Form',
				'name' => 'contact_form',
				'type' => 'acf_cf7',
				'instructions' => 'Select which form from the Contact Form 7 plugin you want to use for the contact page. If there is no forms to select then you need to create one first via the plugin.',
				'allow_null' => 0,
				'multiple' => 0,
				'disable' => array (
					0 => 0,
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/template-contact.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 3,
	));
	register_field_group(array (
		'id' => 'acf_portfolio-project-details',
		'title' => 'Portfolio Project Details',
		'fields' => array (
			array (
				'key' => 'field_52f8cd8b9868a',
				'label' => 'Client Name',
				'name' => 'client_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52f8ce485bcf5',
				'label' => 'Project Description',
				'name' => 'project_description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_52f8cdb99868b',
				'label' => 'Project Date',
				'name' => 'project_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_52f8ce9128c46',
				'label' => 'Project URL',
				'name' => 'project_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_530746a588dca',
				'label' => 'Featured Project',
				'name' => 'featured_project',
				'type' => 'true_false',
				'instructions' => 'Select if you want this project to be shown within the featured projects slider on the portfolio home page.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5315c0b0a90bc',
				'label' => 'Double Size',
				'name' => 'double_size',
				'type' => 'true_false',
				'instructions' => 'Select if you want to make this portfolio item double the size compared to the other items on the portfolio home page. This is a great way to make certain items stand out from the rest.',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 3,
	));
	register_field_group(array (
		'id' => 'acf_google-analytics',
		'title' => 'Google Analytics',
		'fields' => array (
			array (
				'key' => 'field_52fa3a55c9a4e',
				'label' => 'Google Analytics Embed Code',
				'name' => 'analytics_code',
				'type' => 'textarea',
				'instructions' => 'Add your Google Analytics tracking code here',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
				'rows' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 4,
	));
}
